<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>maude</string>
	</array>
	<key>name</key>
	<string>Maude</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\*\*\*\(</string>
			<key>end</key>
			<string>\)$</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\*\*\*)|(---)).*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mod|fmod|omod|endm|endfm|endm|is)\b</string>
			<key>name</key>
			<string>keyword.control.module</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(protecting|including|extending)\b</string>
			<key>name</key>
			<string>keyword.control.imports</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sort|subsort|sorts|subsorts)\b</string>
			<key>name</key>
			<string>keyword.control.sorts</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(op|ops|var|vars|eq|ceq)\b</string>
			<key>name</key>
			<string>keyword.control.statements</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Bool|Nat|Zero|NzNat|Int|NzInt|Rat|PosRat|NzRat|Float|FiniteFloat|String|Char|Qid|List\{.+\}|NeList\{.+\}|NatList|Bool|Universal)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|fi)\b</string>
			<key>name</key>
			<string>keyword.control.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:|(\-\&gt;)|=|\/\\|\&lt;|\&gt;)|(\.\s*$)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.maude</string>
	<key>uuid</key>
	<string>7eb79cba-93e0-4258-8f40-b78359ca29b2</string>
</dict>
</plist>
